{{/*
Generates deployment specs for K10 services and other services such as
"frontend" and "kanister".
*/}}
{{- include "singleAuth.check" . -}}
{{- $main_context := . -}}
{{- $stateless_services := include "k10.statelessServices" . | splitList " " -}}
{{- range $skip, $k10_service := include "k10.restServices" . | splitList " " }}
  {{/* Set $stateful for stateful services when .Values.global.persistence.enabled is true */}}
  {{- $stateful := and $.Values.global.persistence.enabled (not (has $k10_service $stateless_services)) -}}
  {{/* Set $replicas to .Values.executorReplicas for the exectutor service */}}
  {{- $replicas := or (and (eq $k10_service "executor") $.Values.executorReplicas) 1 -}}
  {{ $tmp_contx := dict "main" $main_context "k10_service" $k10_service "stateful" $stateful "replicas" $replicas }}
  {{ if eq $k10_service "metering" }}
    {{- include "k10-metering" $tmp_contx -}}
  {{ else }}
    {{- include "k10-default" $tmp_contx -}}
  {{ end }}
{{- end }}
{{/*
Generate deployment specs for additional services. These are stateless and have
1 replica.
*/}}
{{- range $skip, $k10_service := concat (include "k10.services" . | splitList " ") (include "k10.additionalServices" . | splitList " ") }}
  {{ $tmp_contx := dict "main" $main_context "k10_service" $k10_service "stateful" false "replicas" 1 }}
  {{- include "k10-default" $tmp_contx -}}
{{- end }}
