{{- $main := . -}}
{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: {{ .Release.Namespace }}-{{ template "serviceAccountName" . }}-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- if not ( eq (include "meteringServiceAccountName" .) (include "serviceAccountName" .) )}}
- kind: ServiceAccount
  name: {{ template "meteringServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: {{ .Release.Name }}-admin
rules:
- apiGroups:
{{- range include "k10.configAPIs" $main | splitList " "  }}
  - {{ . }}.{{ template "apiDomain" $main }}
{{- end }}
{{- range include "k10.aggregatedAPIs" $main | splitList " "  }}
  - {{ . }}.{{ template "apiDomain" $main }}
{{- end }}
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - cr.kanister.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: {{ .Release.Name }}-ns-admin
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - deployments
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
- apiGroups:
  - "batch"
  resources:
  - jobs
  verbs:
  - get
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: {{ .Release.Name }}-mc-admin
rules:
- apiGroups:
{{- range include "k10.configAPIs" $main | splitList " "  }}
  - {{ . }}.{{ template "apiDomain" $main }}
{{- end }}
{{- range include "k10.distAPIs" $main | splitList " "  }}
  - {{ . }}.{{ template "apiDomain" $main }}
{{- end }}
{{- range include "k10.authAPIs" $main | splitList " "  }}
  - {{ . }}.{{ template "apiDomain" $main }}
{{- end }}
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: {{ .Release.Name }}-basic
rules:
- apiGroups:
{{- range include "k10.actionsAPIs" $main | splitList " "  }}
  - {{ . }}.{{ template "apiDomain" $main }}
{{- end }}
  resources:
  - {{ include "k10.backupActions" $main}}
  - {{ include "k10.backupActionsDetails" $main}}
  - {{ include "k10.restoreActions" $main}}
  - {{ include "k10.restoreActionsDetails" $main}}
  - {{ include "k10.exportActions" $main}}
  - {{ include "k10.exportActionsDetails" $main}}
  - {{ include "k10.cancelActions" $main}}
  verbs:
   - "*"
- apiGroups:
{{- range include "k10.appsAPIs" $main | splitList " "  }}
  - {{ . }}.{{ template "apiDomain" $main }}
{{- end }}
  resources:
  - {{ include "k10.restorePoints" $main}}
  - {{ include "k10.restorePointsDetails" $main}}
  - {{ include "k10.applications" $main}}
  - {{ include "k10.applicationsDetails" $main}}
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
{{- range include "k10.configAPIs" $main | splitList " "  }}
  - {{ . }}.{{ template "apiDomain" $main }}
{{- end }}
  resources:
  - {{ include "k10.policies" $main}}
  verbs:
  - "*"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: {{ .Release.Name }}-config-view
rules:
- apiGroups:
{{- range include "k10.configAPIs" $main | splitList " "  }}
  - {{ . }}.{{ template "apiDomain" $main }}
{{- end }}
  resources:
  - {{ include "k10.profiles" $main}}
  - {{ include "k10.policies" $main}}
  verbs:
  - get
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: {{ .Release.Namespace }}-{{ template "serviceAccountName" . }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ .Release.Name }}-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: k10:admins
{{- range .Values.auth.k10AdminUsers }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . }}
{{- end }}
{{- range default .Values.auth.groupAllowList .Values.auth.k10AdminGroups }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ . }}
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
  name: {{ .Release.Namespace }}-{{ template "serviceAccountName" . }}-ns-admin
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  {{ .Release.Name }}-ns-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: k10:admins
{{- range .Values.auth.k10AdminUsers }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . }}
{{- end }}
{{- range default .Values.auth.groupAllowList .Values.auth.k10AdminGroups }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ . }}
{{- end }}
{{- end }}
