# Default values for trident-ontap-nas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
#
# aff400-secret.yaml
username: admin
password: SAPhana20!

# backend-tbc-ontap-nas.yaml
managementLIF: 172.18.1.25
dataLIF: 172.18.2.222
backendName: aff400-nas
svm: POD4_IKS

# storage-class-csi.yaml
sc_name: pod4-iks-nas-csi
