# Default values for trident-ontap-nas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
#
# aff-secret.yaml
username: admin
password: netapp123

# backend-tbc-ontap-nas.yaml
# Management LIF IP address for the storage used (cluster IP on e0M)
managementLIF: 10.10.48.10

# Data LIF IP address of the storage VM used for NFS 
dataLIF: 10.10.50.91

# NAme of the SVM/vserver on the storage
svm: FlexPod-Trident

# Name of the Storage used in Kubernetes cluster
backendName: aff700-nas


# storage-class-csi.yaml
sc_name: fp-nas-csi
