# Default values for trident-ontap-nas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
#
# aff400-secret.yaml
username: admin
password: SAPhana20!

# backend-tbc-ontap-nas.yaml
# Management LIF IP address for the storage used (cluster IP on e0M)
managementLIF: 172.28.0.149

# Data LIF IP address of the storage VM used for NFS 
dataLIF: 172.29.5.50

# NAme of the SVM/vserver on the storage
svm: infra

# Name of the Storage used in Kubernetes cluster
backendName: aff300-nas


# storage-class-csi.yaml
sc_name: fp-nas-csi
