apiVersion: v1
kind: Secret
metadata:
  name: backend-tbc-ontap-nas-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
