apiVersion: v1
kind: Secret
metadata:
  name: k10-vsphere-infra-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  vsphere_user: {{ .Values.vsphere_user }}
  vsphere_password: {{ .Values.vsphere_password }}

---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: {{ .Values.vsphere_profile_name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: Infra
  infra:
    type: VSphere
    vsphere:
      serverAddress: {{ .Values.vsphere_addr }}
    credential:
      secretType: VSphereKey
      secret:
        apiVersion: v1
        kind: Secret
        name: k10-vsphere-infra-secret
        namespace: {{ .Release.Namespace }}
