apiVersion: config.kio.kasten.io/v1alpha1
kind: Policy
metadata:
  name: {{ .Values.system_policy_name }}
  namespace: {{ .Release.Namespace }}
spec:
  comment: system backup policy
  frequency: '@hourly'
  retention:
    hourly: 24
    daily: 7
  actions:
  - action: backup
    backupParameters:
      filters: {}
      profile:
        name: {{ .Values.sg_profile_name }}
        namespace: {{ .Release.Namespace }}
  - action: export
    exportParameters:
      exportData:
        enabled: true
      frequency: '@hourly'
      profile:
        name: {{ .Values.sg_profile_name }}
        namespace: {{ .Release.Namespace }}
      blockModeProfile:
        name: {{ .Values.vbr_profile_name }}
        namespace: {{ .Release.Namespace }}
  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values: 
      - iks
      - rafay-system
      - rafay-infra
      - trident
      - cluster-registry
