apiVersion: v1
kind: Secret
metadata:
  name: k10-vbr-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  vbr_user: {{ .Values.vbr_user }}
  vbr_password: {{ .Values.vbr_password }}

---
apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: {{ .Values.vbr_profile_name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: Location
  locationSpec:
    credential:
      secretType: VBRKey
      secret:
        apiVersion: v1
        kind: Secret
        name: k10-vbr-secret
        namespace: {{ .Release.Namespace }}
    type: VBR
    vbr:
      repoName: {{ .Values.vbr_repo_name }}
      serverAddress: {{ .Values.vbr_ip }}
      serverPort: {{ .Values.vbr_port }}
      skipSSLVerify: true
