apiVersion: v1
kind: Service
metadata:
  name: basyx-mqtt-broker-service
spec:
  selector:
    app: basyx-aas
  ports:
    - protocol: TCP
      name: mqtt-broker-port-1
      port: 1883
      targetPort: 1883
    - protocol: TCP
      name: mqtt-broker-port-2
      port: 5001
      targetPort: 5001
    - protocol: TCP
      name: mqtt-broker-port-3
      port: 9001
      targetPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basyx-mqtt-broker-deployment
  labels:
    app: basyx-aas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basyx-aas
  template:
    metadata:
      labels:
        app: basyx-aas
    spec:
      imagePullSecrets:
        - name: erbenschell
      containers:
        - name: basyx-mqtt-broker
          image: registry.erbenschell.iese.fraunhofer.de/basyx/minimalinfrastructure/mqtt-broker:latest
          ports:
            - containerPort: 1883
            - containerPort: 9001
            - containerPort: 5001
